/*
# Nebula Configuration service for NEST (Nebula Enrollment over Secure Transport) - OpenAPI 3.0
This is a simple Nebula Configuration service that generates Nebula configuration files from Dhall configuration files on behalf of the NEST service

API version: 0.3.1
Contact: gianmarco.decola@studio.unibo.it
*/
package conf

import (
	"github.com/m4rkdc/nebula_est/pkg/models"
)

var (
	//Folder containing dhall-specific files used by the dhall-nebula tool
	Dhall_dir string = "dhall/"
	//File containing the general NEST client Nebula network specifications
	Dhall_configuration string = Dhall_dir + "nebula/nebula_conf.dhall"
	//Folder containing the NEST clients Nebula configuration files generated by this service
	Conf_gen_dir string = Dhall_dir + "nebula/generated/"
	//This service's log file
	Log_file string = "log/nest_config.log"
	//This service's IP address on the NEST SYSTEM Nebula network
	Service_ip string = "192.168.80.3"
	//This service's port on the NEST SYSTEM Nebula network
	Service_port string = "61616"
	//Folder containing this service's NEST system Nebula network keys and configurations
	Nebula_folder string = "config/nebula/"
)

// Conf_routes contains the routes considered by the nest_config router
var Conf_routes = [3]models.Route{
	{
		Name:        "GetConfig",
		Method:      "GET",
		Pattern:     "configs/:hostname",
		HandlerFunc: GetConfig,
	},
	{
		Name:        "GetValidHostnames",
		Method:      "GET",
		Pattern:     "/hostnames",
		HandlerFunc: GetValidHostnames,
	}, /*
		{
			Name:        "ValidateCertificate",
			Method:      "POST",
			Pattern:     "/validate",
			HandlerFunc: ValidateCertificate,
		},*/
}
